/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppTagsRouteImport } from './routes/_app/tags'
import { Route as AppExercisesRouteImport } from './routes/_app/exercises'
import { Route as AppPlansIndexRouteImport } from './routes/_app/plans/index'
import { Route as AppTemplatesTemplateIdRouteImport } from './routes/_app/templates/$templateId'
import { Route as AppPlansPlanIdRouteImport } from './routes/_app/plans/$planId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppTagsRoute = AppTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AppRoute,
} as any)
const AppExercisesRoute = AppExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansIndexRoute = AppPlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesTemplateIdRoute = AppTemplatesTemplateIdRouteImport.update({
  id: '/templates/$templateId',
  path: '/templates/$templateId',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansPlanIdRoute = AppPlansPlanIdRouteImport.update({
  id: '/plans/$planId',
  path: '/plans/$planId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/exercises': typeof AppExercisesRoute
  '/tags': typeof AppTagsRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/plans/$planId': typeof AppPlansPlanIdRoute
  '/templates/$templateId': typeof AppTemplatesTemplateIdRoute
  '/plans/': typeof AppPlansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/exercises': typeof AppExercisesRoute
  '/tags': typeof AppTagsRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/plans/$planId': typeof AppPlansPlanIdRoute
  '/templates/$templateId': typeof AppTemplatesTemplateIdRoute
  '/plans': typeof AppPlansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/exercises': typeof AppExercisesRoute
  '/_app/tags': typeof AppTagsRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/': typeof AppIndexRoute
  '/_app/plans/$planId': typeof AppPlansPlanIdRoute
  '/_app/templates/$templateId': typeof AppTemplatesTemplateIdRoute
  '/_app/plans/': typeof AppPlansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exercises'
    | '/tags'
    | '/login'
    | '/register'
    | '/plans/$planId'
    | '/templates/$templateId'
    | '/plans/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exercises'
    | '/tags'
    | '/login'
    | '/register'
    | '/plans/$planId'
    | '/templates/$templateId'
    | '/plans'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/exercises'
    | '/_app/tags'
    | '/_auth/login'
    | '/_auth/register'
    | '/_app/'
    | '/_app/plans/$planId'
    | '/_app/templates/$templateId'
    | '/_app/plans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/tags': {
      id: '/_app/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof AppTagsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exercises': {
      id: '/_app/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof AppExercisesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plans/': {
      id: '/_app/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof AppPlansIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates/$templateId': {
      id: '/_app/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof AppTemplatesTemplateIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plans/$planId': {
      id: '/_app/plans/$planId'
      path: '/plans/$planId'
      fullPath: '/plans/$planId'
      preLoaderRoute: typeof AppPlansPlanIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppExercisesRoute: typeof AppExercisesRoute
  AppTagsRoute: typeof AppTagsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPlansPlanIdRoute: typeof AppPlansPlanIdRoute
  AppTemplatesTemplateIdRoute: typeof AppTemplatesTemplateIdRoute
  AppPlansIndexRoute: typeof AppPlansIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppExercisesRoute: AppExercisesRoute,
  AppTagsRoute: AppTagsRoute,
  AppIndexRoute: AppIndexRoute,
  AppPlansPlanIdRoute: AppPlansPlanIdRoute,
  AppTemplatesTemplateIdRoute: AppTemplatesTemplateIdRoute,
  AppPlansIndexRoute: AppPlansIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
