/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppTargetsRouteImport } from './routes/_app/targets'
import { Route as AppTagsRouteImport } from './routes/_app/tags'
import { Route as AppStatsRouteImport } from './routes/_app/stats'
import { Route as AppSessionRouteImport } from './routes/_app/session'
import { Route as AppFoodsRouteImport } from './routes/_app/foods'
import { Route as AppExercisesRouteImport } from './routes/_app/exercises'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppRecipesIndexRouteImport } from './routes/_app/recipes/index'
import { Route as AppPlansIndexRouteImport } from './routes/_app/plans/index'
import { Route as AppHistoryIndexRouteImport } from './routes/_app/history/index'
import { Route as AppTemplatesTemplateIdRouteImport } from './routes/_app/templates/$templateId'
import { Route as AppRecipesNewRouteImport } from './routes/_app/recipes/new'
import { Route as AppRecipesRecipeIdRouteImport } from './routes/_app/recipes/$recipeId'
import { Route as AppPlansPlanIdRouteImport } from './routes/_app/plans/$planId'
import { Route as AppHistorySessionIdRouteImport } from './routes/_app/history/$sessionId'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppTargetsRoute = AppTargetsRouteImport.update({
  id: '/targets',
  path: '/targets',
  getParentRoute: () => AppRoute,
} as any)
const AppTagsRoute = AppTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AppRoute,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionRoute = AppSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => AppRoute,
} as any)
const AppFoodsRoute = AppFoodsRouteImport.update({
  id: '/foods',
  path: '/foods',
  getParentRoute: () => AppRoute,
} as any)
const AppExercisesRoute = AppExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesIndexRoute = AppRecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansIndexRoute = AppPlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryIndexRoute = AppHistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesTemplateIdRoute = AppTemplatesTemplateIdRouteImport.update({
  id: '/templates/$templateId',
  path: '/templates/$templateId',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesNewRoute = AppRecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesRecipeIdRoute = AppRecipesRecipeIdRouteImport.update({
  id: '/recipes/$recipeId',
  path: '/recipes/$recipeId',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansPlanIdRoute = AppPlansPlanIdRouteImport.update({
  id: '/plans/$planId',
  path: '/plans/$planId',
  getParentRoute: () => AppRoute,
} as any)
const AppHistorySessionIdRoute = AppHistorySessionIdRouteImport.update({
  id: '/history/$sessionId',
  path: '/history/$sessionId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/calendar': typeof AppCalendarRoute
  '/exercises': typeof AppExercisesRoute
  '/foods': typeof AppFoodsRoute
  '/session': typeof AppSessionRoute
  '/stats': typeof AppStatsRoute
  '/tags': typeof AppTagsRoute
  '/targets': typeof AppTargetsRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/history/$sessionId': typeof AppHistorySessionIdRoute
  '/plans/$planId': typeof AppPlansPlanIdRoute
  '/recipes/$recipeId': typeof AppRecipesRecipeIdRoute
  '/recipes/new': typeof AppRecipesNewRoute
  '/templates/$templateId': typeof AppTemplatesTemplateIdRoute
  '/history/': typeof AppHistoryIndexRoute
  '/plans/': typeof AppPlansIndexRoute
  '/recipes/': typeof AppRecipesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/calendar': typeof AppCalendarRoute
  '/exercises': typeof AppExercisesRoute
  '/foods': typeof AppFoodsRoute
  '/session': typeof AppSessionRoute
  '/stats': typeof AppStatsRoute
  '/tags': typeof AppTagsRoute
  '/targets': typeof AppTargetsRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/history/$sessionId': typeof AppHistorySessionIdRoute
  '/plans/$planId': typeof AppPlansPlanIdRoute
  '/recipes/$recipeId': typeof AppRecipesRecipeIdRoute
  '/recipes/new': typeof AppRecipesNewRoute
  '/templates/$templateId': typeof AppTemplatesTemplateIdRoute
  '/history': typeof AppHistoryIndexRoute
  '/plans': typeof AppPlansIndexRoute
  '/recipes': typeof AppRecipesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/exercises': typeof AppExercisesRoute
  '/_app/foods': typeof AppFoodsRoute
  '/_app/session': typeof AppSessionRoute
  '/_app/stats': typeof AppStatsRoute
  '/_app/tags': typeof AppTagsRoute
  '/_app/targets': typeof AppTargetsRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/': typeof AppIndexRoute
  '/_app/history/$sessionId': typeof AppHistorySessionIdRoute
  '/_app/plans/$planId': typeof AppPlansPlanIdRoute
  '/_app/recipes/$recipeId': typeof AppRecipesRecipeIdRoute
  '/_app/recipes/new': typeof AppRecipesNewRoute
  '/_app/templates/$templateId': typeof AppTemplatesTemplateIdRoute
  '/_app/history/': typeof AppHistoryIndexRoute
  '/_app/plans/': typeof AppPlansIndexRoute
  '/_app/recipes/': typeof AppRecipesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/exercises'
    | '/foods'
    | '/session'
    | '/stats'
    | '/tags'
    | '/targets'
    | '/login'
    | '/register'
    | '/history/$sessionId'
    | '/plans/$planId'
    | '/recipes/$recipeId'
    | '/recipes/new'
    | '/templates/$templateId'
    | '/history/'
    | '/plans/'
    | '/recipes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/exercises'
    | '/foods'
    | '/session'
    | '/stats'
    | '/tags'
    | '/targets'
    | '/login'
    | '/register'
    | '/history/$sessionId'
    | '/plans/$planId'
    | '/recipes/$recipeId'
    | '/recipes/new'
    | '/templates/$templateId'
    | '/history'
    | '/plans'
    | '/recipes'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/calendar'
    | '/_app/exercises'
    | '/_app/foods'
    | '/_app/session'
    | '/_app/stats'
    | '/_app/tags'
    | '/_app/targets'
    | '/_auth/login'
    | '/_auth/register'
    | '/_app/'
    | '/_app/history/$sessionId'
    | '/_app/plans/$planId'
    | '/_app/recipes/$recipeId'
    | '/_app/recipes/new'
    | '/_app/templates/$templateId'
    | '/_app/history/'
    | '/_app/plans/'
    | '/_app/recipes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/targets': {
      id: '/_app/targets'
      path: '/targets'
      fullPath: '/targets'
      preLoaderRoute: typeof AppTargetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tags': {
      id: '/_app/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof AppTagsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stats': {
      id: '/_app/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/session': {
      id: '/_app/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof AppSessionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/foods': {
      id: '/_app/foods'
      path: '/foods'
      fullPath: '/foods'
      preLoaderRoute: typeof AppFoodsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exercises': {
      id: '/_app/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof AppExercisesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes/': {
      id: '/_app/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof AppRecipesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plans/': {
      id: '/_app/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof AppPlansIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history/': {
      id: '/_app/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof AppHistoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates/$templateId': {
      id: '/_app/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof AppTemplatesTemplateIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes/new': {
      id: '/_app/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof AppRecipesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes/$recipeId': {
      id: '/_app/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof AppRecipesRecipeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plans/$planId': {
      id: '/_app/plans/$planId'
      path: '/plans/$planId'
      fullPath: '/plans/$planId'
      preLoaderRoute: typeof AppPlansPlanIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history/$sessionId': {
      id: '/_app/history/$sessionId'
      path: '/history/$sessionId'
      fullPath: '/history/$sessionId'
      preLoaderRoute: typeof AppHistorySessionIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppExercisesRoute: typeof AppExercisesRoute
  AppFoodsRoute: typeof AppFoodsRoute
  AppSessionRoute: typeof AppSessionRoute
  AppStatsRoute: typeof AppStatsRoute
  AppTagsRoute: typeof AppTagsRoute
  AppTargetsRoute: typeof AppTargetsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppHistorySessionIdRoute: typeof AppHistorySessionIdRoute
  AppPlansPlanIdRoute: typeof AppPlansPlanIdRoute
  AppRecipesRecipeIdRoute: typeof AppRecipesRecipeIdRoute
  AppRecipesNewRoute: typeof AppRecipesNewRoute
  AppTemplatesTemplateIdRoute: typeof AppTemplatesTemplateIdRoute
  AppHistoryIndexRoute: typeof AppHistoryIndexRoute
  AppPlansIndexRoute: typeof AppPlansIndexRoute
  AppRecipesIndexRoute: typeof AppRecipesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppExercisesRoute: AppExercisesRoute,
  AppFoodsRoute: AppFoodsRoute,
  AppSessionRoute: AppSessionRoute,
  AppStatsRoute: AppStatsRoute,
  AppTagsRoute: AppTagsRoute,
  AppTargetsRoute: AppTargetsRoute,
  AppIndexRoute: AppIndexRoute,
  AppHistorySessionIdRoute: AppHistorySessionIdRoute,
  AppPlansPlanIdRoute: AppPlansPlanIdRoute,
  AppRecipesRecipeIdRoute: AppRecipesRecipeIdRoute,
  AppRecipesNewRoute: AppRecipesNewRoute,
  AppTemplatesTemplateIdRoute: AppTemplatesTemplateIdRoute,
  AppHistoryIndexRoute: AppHistoryIndexRoute,
  AppPlansIndexRoute: AppPlansIndexRoute,
  AppRecipesIndexRoute: AppRecipesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
